//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Give_Feedback
    {
        public int ID { get; set; }
        public int Team_Leader_ID { get; set; }
        public int Project_Manager_ID { get; set; }
        public string Feedback { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
