//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Make_Report
    {
        [Key]
        public int ID { get; set; }
        public int Customer_ID { get; set; }
        public int Project_Manager_ID { get; set; }
        [Display(Name ="Report Details")]
        [Required(ErrorMessage ="Please Tell us more explaination")]
        public string Report { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
