//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_type
    {
        public int ID { get; set; }
        public int Project_ID { get; set; }
        public int Pro_type { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
