//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sending_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sending_Request()
        {
            this.Responding_Request = new HashSet<Responding_Request>();
        }
    
        public int ID { get; set; }
        public int Sender_ID { get; set; }
        public int Reciever_ID { get; set; }
        public int Project_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responding_Request> Responding_Request { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
