//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;
   

    public partial class User
    {
       [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "User name is required")]
        [Display(Name = "User Name")]
        public string User_Name { get; set; }


        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [MinLength(6,ErrorMessage ="Password length must be at least 6 ")]
        public string password { get; set; }


        [Required(ErrorMessage = "Email is required")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Enter a valid Email ")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public byte[] Photo { get; set; }


        [Required(ErrorMessage = "please upload your photo")]
        [Display(Name = "Upload your photo")]

        public HttpPostedFileBase File { get; set; }

        [HiddenInput(DisplayValue = false)]
        [Required(ErrorMessage = "Please enter the job Description ")]
        [Display(Name = "Job Description")]
        public string Job_Description { get; set; }


        [Required(ErrorMessage = "First name is required")]
        [Display(Name = "First Name")]
        public string First_Name { get; set; }


        [Required(ErrorMessage = "Last name is required")]
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }


        [Required(ErrorMessage = "please enter a phone number ")]
        [DataType(DataType.PhoneNumber)]
        public int Mobile { get; set; }

        [Required(ErrorMessage = "please determine the new user privileges")]
        [HiddenInput(DisplayValue = false)]
        public int Type { get; set; }


        [Display(Name ="Confirm Password")]
        [DataType(DataType.Password)]
        [System.ComponentModel.DataAnnotations.Compare("password", ErrorMessage = "password don not match ")]
        public string confirmpassword { get; set; }

        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
    }
}
